In [1]:
import subprocess
from datetime import datetime
from IPython import get_ipython

# --- CONFIGURATION ---
NOTEBOOK_NAME = "Basics_Of_NumPy.ipynb"  # ← 🔁 Change this per notebook
PLUGIN_NAME = "jupyterlab/4.0.0"
LANGUAGE = "Python"
# ----------------------

def log_to_wakatime():
    timestamp = str(datetime.utcnow().timestamp())
    result = subprocess.run([
        "wakatime-cli",
        "--entity", NOTEBOOK_NAME,
        "--entity-type", "file",
        "--plugin", PLUGIN_NAME,
        "--language", LANGUAGE,
        "--write",
        "--time", timestamp
    ], capture_output=True, text=True)

    if result.returncode != 0:
        print("❌ WakaTime CLI Error:")
        print("STDOUT:", result.stdout)
        print("STDERR:", result.stderr)
    else:
        print("✅ WakaTime heartbeat sent at", timestamp)

def on_cell_run(execution_info):
    log_to_wakatime()

# Clear broken old handlers (if rerunning)
ip = get_ipython()
for cb in list(ip.events.callbacks['pre_run_cell']):
    if cb.__name__ == "<lambda>":
        ip.events.unregister('pre_run_cell', cb)

ip.events.register('pre_run_cell', on_cell_run)


In [2]:
import numpy as np

✅ WakaTime heartbeat sent at 1751466382.635582


# To Create Array from List

In [3]:
lst = [1,2,3,4,5]
arr = np.array(lst)
print(arr)

✅ WakaTime heartbeat sent at 1751466386.996372
[1 2 3 4 5]


In [4]:
lst = [[1, 2], [3, 4], [5, 6]]
arr = np.array(lst)
print(arr)

✅ WakaTime heartbeat sent at 1751466387.060882
[[1 2]
 [3 4]
 [5 6]]


# Basic Array Creation Methods

| Method             | Description                        |
| ------------------ | ---------------------------------- |
| `zeros()`          | Array of all zeros                 |
| `ones()`           | Array of all ones                  |
| `empty()`          | Uninitialized array                |
| `full()`           | Array filled with a constant       |
| `arange()`         | Range of evenly spaced values      |
| `linspace()`       | Evenly spaced values over interval |
| `eye()`            | Identity matrix                    |
| `random.rand()`    | Random values in \[0, 1)           |
| `random.randint()` | Random integers                    |


### ```np.arange(start,end)```  Creates array from start to end-1

In [5]:
np.arange(0,10) 

✅ WakaTime heartbeat sent at 1751466387.119684


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### ```np.arange(start,end,skip)``` Creates array from start to end-1 with a interval of skip

In [6]:
np.arange(0,10,2) 

✅ WakaTime heartbeat sent at 1751466387.179007


array([0, 2, 4, 6, 8])

### ```np.arange(end)``` Creates an array from 0 to end-1

In [7]:
np.arange(10) 

✅ WakaTime heartbeat sent at 1751466387.269568


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### ```np.eye(n)``` Creates an Identity Matrix of order n

In [8]:
np.eye(4) 

✅ WakaTime heartbeat sent at 1751466387.327212


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### ```np.zeros((M,N))```  Creates M x N matrix filled with zeroes

### The function np.zeros() takes a single argument called shape, which must be a tuple.
| Syntax             | Meaning                                      | Valid?  |
| ------------------ | -------------------------------------------- | ------- |
| `np.zeros(4)`      | Creates a 1D array with 4 zeros              | ✅ Yes   |
| `np.zeros((4, 3))` | Creates a 2D array with 4 rows and 3 columns | ✅ Yes   |
| `np.zeros(4, 3)`   | Passes two arguments, not a tuple            | ❌ Error |


In [9]:
np.zeros((4,3)) 

✅ WakaTime heartbeat sent at 1751466387.387961


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

###  ``` no.ones((M,N)) ```  Creates M x N matrix filles with ones

### The function np.ones() takes a single argument called shape, which must be a tuple.
| Syntax             | Meaning                                      | Valid?  |
| ------------------ | -------------------------------------------- | ------- |
| `np.ones(4)`      | Creates a 1D array with 4 ones              | ✅ Yes   |
| `np.ones((4, 3))` | Creates a 2D array with 4 rows and 3 columns | ✅ Yes   |
| `np.ones(4, 3)`   | Passes two arguments, not a tuple            | ❌ Error |


In [10]:
np.ones((4,3)) 

✅ WakaTime heartbeat sent at 1751466387.446602


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### ```np.full((M,N),X)``` Creates a M x N matrix filled with X

In [11]:
np.full((4,3),'a')

✅ WakaTime heartbeat sent at 1751466387.504558


array([['a', 'a', 'a'],
       ['a', 'a', 'a'],
       ['a', 'a', 'a'],
       ['a', 'a', 'a']], dtype='<U1')

In [12]:
np.full((4,3),7)

✅ WakaTime heartbeat sent at 1751466387.564534


array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

### ```np.linspace(start,end)``` Returns evenly spaced numbers over a range from start to end.
numpy.linspace(start, stop, num)
| Parameter | Description                                  |
| --------- | -------------------------------------------- |
| `start`   | The starting value of the sequence           |
| `stop`    | The ending value of the sequence             |
| `num`     | Number of values to generate (default is 50) |


In [13]:
np.linspace(1,10,25)

✅ WakaTime heartbeat sent at 1751466387.621428


array([ 1.   ,  1.375,  1.75 ,  2.125,  2.5  ,  2.875,  3.25 ,  3.625,
        4.   ,  4.375,  4.75 ,  5.125,  5.5  ,  5.875,  6.25 ,  6.625,
        7.   ,  7.375,  7.75 ,  8.125,  8.5  ,  8.875,  9.25 ,  9.625,
       10.   ])

In [14]:
np.linspace(0,100)

✅ WakaTime heartbeat sent at 1751466387.678134


array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])


###  `np.empty(shape, dtype=float)`

- 🔹 Creates an uninitialized array of given shape and dtype.
- 🔸 Values are random **garbage** left in memory — **not zeros**.


In [26]:
arr = np.empty((2, 3))
print(arr)

✅ WakaTime heartbeat sent at 1751467012.9859
[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]]


###  `np.random.rand(d0, d1, ..., dn)`

- 🔹 Returns random **float values** in the range **[0.0, 1.0)**.
- 🔸 Shape is provided as **multiple arguments**, not a tuple.


In [27]:
arr = np.random.rand(2, 3)
print(arr)

✅ WakaTime heartbeat sent at 1751467016.670408
[[0.95116826 0.0847772  0.28141995]
 [0.60709169 0.80699476 0.41675391]]


### 🎲 `np.random.randint(low, high=None, size=None, dtype=int)`

- 🔹 Returns random **integers** from `low` (inclusive) to `high` (exclusive).
- 🔸 If `high` is `None`, it returns values from `0` to `low`.
- 📌 You can specify `size` as an int or a tuple to get arrays.


In [31]:
arr = np.random.randint(10, 50, size=(2, 4))
print(arr)

✅ WakaTime heartbeat sent at 1751467092.344091
[[48 41 21 23]
 [18 40 38 20]]


In [ ]:
arr = np.random.randint(5, size=4)  # From 0 to 4
print(arr)


## ‼️Tip: Always seed with `np.random.seed(0)` for reproducible results.
### More details in ```RandomSeed.ipynb```

# Array Attributes
| **Attribute** | **Description**                           | **Example Output** | **For Array** `[[1, 2, 3], [4, 5, 6]]` |
| ------------- | ----------------------------------------- | ------------------ | -------------------------------------- |
| `arr.shape`   | Tuple showing the dimensions (rows, cols) | `(2, 3)`           | 2 rows × 3 columns                     |
| `arr.size`    | Total number of elements                  | `6`                | 2 × 3 = 6 elements                     |
| `arr.dtype`   | Data type of elements                     | `int64` / `int32`  | Based on system architecture           |
| `arr.ndim`    | Number of dimensions (axes)               | `2`                | It's a 2D array                        |

In [15]:
arr = np.array([[10,20,30],[40,50,60]])
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

✅ WakaTime heartbeat sent at 1751466387.736505
(2, 3)
6
int64
2


In [16]:
arr = np.array([10,20,30])
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

✅ WakaTime heartbeat sent at 1751466387.789424
(3,)
3
int64
1


In [17]:
arr = np.array([1,2,'a'])
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

✅ WakaTime heartbeat sent at 1751466387.844387
(3,)
3
<U21
1


In [18]:
arr = np.array(['1','a'])
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

✅ WakaTime heartbeat sent at 1751466387.896658
(2,)
2
<U1
1


In [19]:
arr = np.array([[10, 20, 30,"Divyansh"], [40, 50, 60,45]])

print("Shape:", arr.shape)  
print("Size:", arr.size)     
print("Dimensions:", arr.ndim) 
print("Data type:", arr.dtype) 

# < → Little-endian byte order (relevant for binary data; for strings it's not very important)

# U → Unicode string type (each element is a string)

# 21 → Each string can be up to 21 Unicode characters long

✅ WakaTime heartbeat sent at 1751466387.951427
Shape: (2, 4)
Size: 8
Dimensions: 2
Data type: <U21


# 🧠 NumPy Data Types 

NumPy arrays store data with a specific **dtype** (data type) for performance and memory efficiency.

---

## 1. Integer Types

| Type     | Description             | Range (Signed)       | Example |
|----------|-------------------------|-----------------------|---------|
| int8     | 8-bit signed integer    | -128 to 127           | `np.array([1], dtype='int8')` |
| int16    | 16-bit signed integer   | -32,768 to 32,767     | `np.array([1], dtype='int16')` |
| int32    | 32-bit signed integer   | ~±2 Billion           | `np.array([1], dtype='int32')` |
| int64    | 64-bit signed integer   | Huge integer support  | `np.array([1], dtype='int64')` |
| uint8–64 | Unsigned versions       | 0 to 255/65535/...    | `np.array([255], dtype='uint8')` |

---

## 2. Floating Point Types

| Type      | Precision       | Example |
|-----------|------------------|---------|
| float16   | Half precision   | `np.array([3.14], dtype='float16')` |
| float32   | Single precision | `np.array([3.14], dtype='float32')` |
| float64   | Double precision | `np.array([3.14], dtype='float64')` |

---

## 3. Complex Number Types

| Type        | Description            | Example |
|-------------|------------------------|---------|
| complex64   | 2 × float32            | `np.array([1+2j], dtype='complex64')` |
| complex128  | 2 × float64            | `np.array([1+2j], dtype='complex128')` |

---

## 4. String Types

| Type     | Description            | Example |
|----------|------------------------|---------|
| str_     | Unicode string         | `np.array(['hello'], dtype='U5')` |
| bytes_   | ASCII/Byte string      | `np.array([b'hi'], dtype='S2')` |

- Unicode string dtype: `'U5'` → 5-character max
- Byte string dtype: `'S5'` → 5-byte ASCII max

---

## 5. Boolean Type

| Type     | Description      | Example |
|----------|------------------|---------|
| bool_    | True / False     | `np.array([True, False], dtype='bool')` |

---

## 6. Date and Time Types

| Type         | Description             | Example |
|--------------|-------------------------|---------|
| datetime64   | Date/time value         | `np.array(['2025-01-01'], dtype='datetime64[D]')` |
| timedelta64  | Time duration           | `np.array([np.datetime64('2025-01-02') - np.datetime64('2025-01-01')])` |

---

# .dtype – Checking Data Type

```python
a = np.array([1, 2, 3])
print(a.dtype)  # Output: int64 (or int32)
````

---

# .astype() – Typecasting After Creation

```python
a = np.array([1.5, 2.8])
b = a.astype(int)      # [1 2]
c = a.astype('float32')  # [1.5 2.8]
d = a.astype(bool)     # [True True]
```

---

# dtype vs astype

| Method      | Purpose                     | When Used                       |
| ----------- | --------------------------- | ------------------------------- |
| `dtype=...` | Typecast **at creation**    | `np.array([...], dtype='int8')` |
| `.astype()` | Typecast **after creation** | `arr.astype('float64')`         |

# 🔁 `.dtype` vs `.astype()` in NumPy – Comparison Table

| Feature               | `.dtype`                          | `.astype()`                           |
|-----------------------|-----------------------------------|----------------------------------------|
| Purpose            | Check data type of array          | Convert array to a different data type |
|  Typecasts            | At Creation                       | After Creation                         |
| Returns            | Data type (e.g., `int64`, `float32`) | A new array with changed data type     |
| Does it modify array? | No                            | No (returns a copy)                  |
| Usage Example      | `arr.dtype`                       | `arr.astype('float32')`                |
| Example Output     | `'int32'`, `'float64'`, `'bool'`  | New array with converted values        |
| Common Use Cases   | Debugging, type checks            | Type casting, preparing data           |

---

# Mixed-Type Input

```python
np.array([1, 2.5, 'hello'])  # dtype='<U32' (string)
```

NumPy will upcast to the most general type (e.g., all to string).

---

# 📦 Summary

* Use `.dtype` to check type
* Use `dtype='...'` or `.astype(...)` to control type
* NumPy arrays are **homogeneous** (all elements same type)
* String and date types are **fixed-width**

---


## `dtype` — **At the Time of Array Creation**

In [20]:
# Create array with dtype specified at creation
arr = np.array([1.5, 2.7, 3.9], dtype='int32')

print("Array:", arr)          # Output: [1 2 3]
print("Data type:", arr.dtype)  # Output: int32

# Here, `dtype='int32'` tells NumPy to convert float values to integers **while creating** the array.


✅ WakaTime heartbeat sent at 1751466388.005387
Array: [1 2 3]
Data type: int32


## `.astype()` — **After Array Creation**

In [21]:
# Create a float array (default)
arr = np.array([1.5, 2.7, 3.9])

# Convert data type after creation
converted = arr.astype('int32')

print("Original array:", arr)           
print("Converted array:", converted)    
print("Converted type:", converted.dtype) 

# `.astype()` is used **after the array is already created**, and returns a **new array** with the new data type.


✅ WakaTime heartbeat sent at 1751466388.058295
Original array: [1.5 2.7 3.9]
Converted array: [1 2 3]
Converted type: int32


# Array Transformation and copy methods

| Method               | Description                              |
| -------------------- | ---------------------------------------- |
| `reshape()`          | Change the shape of the array            |
| `ravel()`            | Flatten to 1D (returns view if possible) |
| `flatten()`          | Flatten to 1D (always returns copy)      |
| `resize()`           | Resize the array in-place                |
| `transpose()` / `.T` | Swap axes / transpose matrix             |
| `squeeze()`          | Remove dimensions of size 1              |
| `expand_dims()`      | Add an axis at a specified position      |
| `swapaxes()`         | Swap two axes                            |
| `moveaxis()`         | Move axes to new positions               |

---

## `reshape()` – Change Array Shape

| Feature          | Description                                      |
|------------------|--------------------------------------------------|
| Purpose          | Reshape array without changing data              |
| Return Type      | View (if possible)                               |
| Requirement      | Total elements must match                        |



In [38]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)

print(b)

✅ WakaTime heartbeat sent at 1751467952.534928
[[1 2 3]
 [4 5 6]]


## `flatten()` – Flatten to 1D (Always Copy)

| Feature          | Description                                      |
|------------------|--------------------------------------------------|
| Purpose          | Convert multi-dimensional array to 1D           |
| Return Type      | Always returns a **copy**                        |
| Affects Original?| ❌ No                                            |

In [23]:
a = np.array([[1, 2], [3, 4]])
b = a.flatten()
b[0] = 100

print(a)  # Original unchanged
print(b)  # [100   2   3   4]

✅ WakaTime heartbeat sent at 1751466388.168519
[[1 2]
 [3 4]]
[100   2   3   4]


## `ravel()` – Flatten to 1D (View if Possible)

| Feature          | Description                                      |
|------------------|--------------------------------------------------|
| Purpose          | Flatten like `flatten()` but returns a **view** if possible |
| Return Type      | View (if memory is contiguous)                   |
| Affects Original?| ✅ Yes (if view)                                 |

In [24]:
a = np.array([[1, 2], [3, 4]])
b = a.ravel()
b[0] = 99

print(a)  # [[99  2]
          #  [ 3  4]]
print(b)  # [99  2  3  4]

✅ WakaTime heartbeat sent at 1751466388.222332
[[99  2]
 [ 3  4]]
[99  2  3  4]


## `copy()` – Create an Independent Clone

| Feature          | Description                                      |
|------------------|--------------------------------------------------|
| Purpose          | Duplicate array with a separate memory           |
| Return Type      | Copy                                             |
| Affects Original?| ❌ No                                            |

In [25]:
a = np.array([10, 20, 30])
b = a.copy()
b[0] = 999

print(a)  # [10 20 30]
print(b)  # [999 20 30]

✅ WakaTime heartbeat sent at 1751466388.280153
[10 20 30]
[999  20  30]


## `resize()`

- 🔹 Modifies the array **in-place** to a new shape.
- 🔸 Fills extra space with **repeated elements** (if needed).

In [41]:
a = np.array([1, 2, 3, 4])
b=a.resize((2, 3))
print(a)

✅ WakaTime heartbeat sent at 1751468056.725346
None


## 🔍 Comparison Summary

| Method     | Purpose              | Returns   | Affects Original | Memory Efficient |
|------------|----------------------|-----------|------------------|------------------|
| `reshape()`| Change shape         | View (if possible) | ✅ Yes (if view) | ✅ Yes |
| `flatten()`| Flatten to 1D        | Copy      | ❌ No            | ❌ No  |
| `ravel()`  | Flatten to 1D        | View (if possible) | ✅ Yes (if view) | ✅ Yes |
| `copy()`   | Duplicate array      | Copy      | ❌ No            | ❌ No  |

**Tip:** Use `.flags` on any array to check if it's writable, a view, and more: