In [1]:
import subprocess
from datetime import datetime
from IPython import get_ipython

# --- CONFIGURATION ---
NOTEBOOK_NAME = "Slicing_and_Indexing.ipynb"
PLUGIN_NAME = "jupyterlab/4.0.0"
LANGUAGE = "Python"
# ----------------------

def log_to_wakatime():
    timestamp = str(datetime.utcnow().timestamp())
    result = subprocess.run([
        "wakatime-cli",
        "--entity", NOTEBOOK_NAME,
        "--entity-type", "file",
        "--plugin", PLUGIN_NAME,
        "--language", LANGUAGE,
        "--write",
        "--time", timestamp
    ], capture_output=True, text=True)

    if result.returncode != 0:
        print("❌ WakaTime CLI Error:")
        print("STDOUT:", result.stdout)
        print("STDERR:", result.stderr)
    else:
        print("✅ WakaTime heartbeat sent at", timestamp)

def on_cell_run(execution_info):
    log_to_wakatime()

# Clear broken old handlers (if rerunning)
ip = get_ipython()
for cb in list(ip.events.callbacks['pre_run_cell']):
    if cb.__name__ == "<lambda>":
        ip.events.unregister('pre_run_cell', cb)

ip.events.register('pre_run_cell', on_cell_run)


In [2]:
import numpy as np 

✅ WakaTime heartbeat sent at 1751520831.486131


# Indexing and Slicing

* Used to **access and manipulate** parts of an array.
* Works for both 1D and multi-dimensional arrays.

### Syntax:

```python
array[start:stop:step]      # slicing
array[index]                # indexing
array[row_index, col_index] # 2D indexing
```


In [3]:
a = np.array([10, 20, 30, 40])
print(a[0])        
print(a[1:3])      
print(a[::-1])     

b = np.array([[1, 2], [3, 4]])
print(b[1][1])     # 
print(b[1, 1])     # (more efficient)

✅ WakaTime heartbeat sent at 1751520831.572501
10
[20 30]
[40 30 20 10]
4
4


In [13]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
 
print(arr,"\n")
print(np.sum(arr, axis=0),"\n")  # Sum along rows (down each column)
print(np.sum(arr, axis=1),"\n")  # Sum along columns (across each row)

✅ WakaTime heartbeat sent at 1751521628.658937
[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[12 15 18] 

[ 6 15 24] 



In [17]:
# Accessing an element
print(arr[1, 2]) # Row index 1, Column index 2 → Output: 6
print(arr[0:2, 1:3])  # Extracts first 2 rows and last 2 columns

✅ WakaTime heartbeat sent at 1751521720.189946
6
[[2 3]
 [5 6]]


In [18]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])

# Output of arr3D.shape is → (depth, rows, columns)
print(arr3D.shape)  # Output: (2, 2, 3) 

# First sheet, second row, third column
print(arr3D[0, 1, 2])  # Output: 6

print(arr3D[:, 0, :])   # Get the first row from both sheets

✅ WakaTime heartbeat sent at 1751522959.121312
(2, 2, 3)
6
[[1 2 3]
 [7 8 9]]


In [19]:
# Get all rows of the first column
first_col = arr[:, 0]
print(first_col)  # Output: [1 4 7]

# Get the first row from each "sheet" in a 3D array
first_rows = arr3D[:, 0, :]
print(first_rows)

✅ WakaTime heartbeat sent at 1751523135.67189
[1 4 7]
[[1 2 3]
 [7 8 9]]


In [20]:
# Replace all elements in column 1 with 0
arr[:, 1] = 0
print(arr)

✅ WakaTime heartbeat sent at 1751523171.583156
[[1 0 3]
 [4 0 6]
 [7 0 9]]


# Boolean Indexing

* Select elements where a **condition is True**.
* Returns a new array.

### Syntax:

```python
array[condition]
```

In [4]:
a = np.array([10, 15, 20, 25])
print(a[a > 15])       
print(a[a % 10 == 0])  

✅ WakaTime heartbeat sent at 1751520831.623447
[20 25]
[10 20]


# Fancy Indexing

* Index arrays using **lists or arrays of indices**.
* Access multiple specific elements.

### Syntax:

```python
array[[i1, i2, i3]]
array[[row_indices], [col_indices]]  # for 2D
```

In [5]:
a = np.array([10, 20, 30, 40, 50])
print(a[[0, 2, 4]])   

b = np.array([[1, 2], [3, 4], [5, 6]])
print(b[[0, 2], [1, 0]]) 

✅ WakaTime heartbeat sent at 1751520831.671414
[10 30 50]
[2 5]


# Broadcasting

* Allows NumPy to perform arithmetic on arrays with **different shapes**.
* The smaller array is **broadcast** to match the shape of the larger one.

### Rules:

1. Dimensions must be equal or 1.
2. Operates element-wise after broadcasting.


In [6]:
a = np.array([1, 2, 3])
print(a + 10)  # [11 12 13]

a = np.array([[1], [2], [3]])
b = np.array([10, 20, 30])
print(a + b)

✅ WakaTime heartbeat sent at 1751520831.718459
[11 12 13]
[[11 21 31]
 [12 22 32]
 [13 23 33]]


# Arithmetic and Comparison

* Perform element-wise math or comparison operations.

###  Common Ops:

```python
+ - * / % // **  ==  !=  >  <  >=  <=
```


In [7]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)  # [5 7 9]
print(a * b)  # [4 10 18]
print(a < b)  # [True True True]

✅ WakaTime heartbeat sent at 1751520831.765116
[5 7 9]
[ 4 10 18]
[ True  True  True]


# Universal Functions (ufuncs)

### 🔹 Theory:

* Optimized **element-wise functions**.
* Fast & vectorized.

### 🔸 Common ufuncs:

```python
np.sqrt(), np.exp(), np.abs(), np.sin(), np.log()
```


In [8]:
a = np.array([1, 4, 9])
print(np.sqrt(a))   # [1. 2. 3.]
print(np.exp(a))    # [2.71 54.6 8103.08]

✅ WakaTime heartbeat sent at 1751520831.811966
[1. 2. 3.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03]


# Aggregation Functions

* Reduce data to a **summary statistic**.

### 🔸 Common:

```python
np.sum(), np.mean(), np.min(), np.max(), np.std()
```


In [9]:
a = np.array([[1, 2], [3, 4]])
print(np.sum(a))    # 10
print(np.mean(a))   # 2.5
print(np.max(a))    # 4

✅ WakaTime heartbeat sent at 1751520831.859991
10
2.5
4


# Axis-wise Operations

* `axis=0`: Column-wise
* `axis=1`: Row-wise


In [10]:
a = np.array([[1, 2], [3, 4]])
print(np.sum(a, axis=0))  # [4 6]
print(np.sum(a, axis=1))  # [3 7]

✅ WakaTime heartbeat sent at 1751520831.906956
[4 6]
[3 7]


# Conditional Functions

###  `np.where(condition, x, y)`

* Returns elements from `x` where `condition` is true, else from `y`.

###  `np.clip(arr, min_val, max_val)`

* Limits array values within bounds.

###  `np.any()` and `np.all()`

* Checks condition across entire array.



In [11]:
a = np.array([1, 2, 3, 4, 5])

print(np.where(a > 3, 1, 0))  # [0 0 0 1 1]
print(np.clip(a, 2, 4))       # [2 2 3 4 4]

print(np.any(a > 4))          # True
print(np.all(a > 0))          # True



✅ WakaTime heartbeat sent at 1751520831.954511
[0 0 0 1 1]
[2 2 3 4 4]
True
True
