In [1]:
import subprocess
from datetime import datetime
from IPython import get_ipython

# --- CONFIGURATION ---
NOTEBOOK_NAME = "Slicing_and_Indexing.ipynb"
PLUGIN_NAME = "jupyterlab/4.0.0"
LANGUAGE = "Python"
# ----------------------

def log_to_wakatime():
    timestamp = str(datetime.utcnow().timestamp())
    result = subprocess.run([
        "wakatime-cli",
        "--entity", NOTEBOOK_NAME,
        "--entity-type", "file",
        "--plugin", PLUGIN_NAME,
        "--language", LANGUAGE,
        "--write",
        "--time", timestamp
    ], capture_output=True, text=True)

    if result.returncode != 0:
        print("❌ WakaTime CLI Error:")
        print("STDOUT:", result.stdout)
        print("STDERR:", result.stderr)
    else:
        print("✅ WakaTime heartbeat sent at", timestamp)

def on_cell_run(execution_info):
    log_to_wakatime()

# Clear broken old handlers (if rerunning)
ip = get_ipython()
for cb in list(ip.events.callbacks['pre_run_cell']):
    if cb.__name__ == "<lambda>":
        ip.events.unregister('pre_run_cell', cb)

ip.events.register('pre_run_cell', on_cell_run)


In [2]:
import numpy as np 

✅ WakaTime heartbeat sent at 1751694140.287308


# Indexing and Slicing

* Used to **access and manipulate** parts of an array.
* Works for both 1D and multi-dimensional arrays.

### Syntax:

```python
array[start:stop:step]      # slicing
array[index]                # indexing
array[row_index, col_index] # 2D indexing
```


In [3]:
a = np.array([10, 20, 30, 40])
print(a[0])        
print(a[1:3])      
print(a[::-1])     

b = np.array([[1, 2], [3, 4]])
print(b[1][1])     # 
print(b[1, 1])     # (more efficient)

✅ WakaTime heartbeat sent at 1751694140.386683
10
[20 30]
[40 30 20 10]
4
4


In [4]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
 
print(arr,"\n")
print(np.sum(arr, axis=0),"\n")  # Sum along rows (down each column)
print(np.sum(arr, axis=1),"\n")  # Sum along columns (across each row)

✅ WakaTime heartbeat sent at 1751694140.450441
[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[12 15 18] 

[ 6 15 24] 



In [5]:
# Accessing an element
print(arr[1, 2]) # Row index 1, Column index 2 → Output: 6
print(arr[0:2, 1:3])  # Extracts first 2 rows and last 2 columns

✅ WakaTime heartbeat sent at 1751694140.514191
6
[[2 3]
 [5 6]]


In [6]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])

# Output of arr3D.shape is → (depth, rows, columns)
print(arr3D.shape)  # Output: (2, 2, 3) 

# First sheet, second row, third column
print(arr3D[0, 1, 2])  # Output: 6

print(arr3D[:, 0, :])   # Get the first row from both sheets

✅ WakaTime heartbeat sent at 1751694140.576811
(2, 2, 3)
6
[[1 2 3]
 [7 8 9]]


In [7]:
# Get all rows of the first column
first_col = arr[:, 0]
print(first_col)  # Output: [1 4 7]

# Get the first row from each "sheet" in a 3D array
first_rows = arr3D[:, 0, :]
print(first_rows)

✅ WakaTime heartbeat sent at 1751694140.639129
[1 4 7]
[[1 2 3]
 [7 8 9]]


In [8]:
# Replace all elements in column 1 with 0
arr[:, 1] = 0
print(arr)

✅ WakaTime heartbeat sent at 1751694140.699756
[[1 0 3]
 [4 0 6]
 [7 0 9]]


# Boolean Indexing

* Select elements where a **condition is True**.
* Returns a new array.

### Syntax:

```python
array[condition]
```

In [9]:
a = np.array([10, 15, 20, 25])
print(a[a > 15])       
print(a[a % 10 == 0])  

✅ WakaTime heartbeat sent at 1751694140.760749
[20 25]
[10 20]


# Fancy Indexing

* Index arrays using **lists or arrays of indices**.
* Access multiple specific elements.

### Syntax:

```python
array[[i1, i2, i3]]
array[[row_indices], [col_indices]]  # for 2D
```

In [10]:
a = np.array([10, 20, 30, 40, 50])
print(a[[0, 2, 4]])   

b = np.array([[1, 2], [3, 4], [5, 6]])
print(b[[0, 2], [1, 0]]) 

✅ WakaTime heartbeat sent at 1751694140.823981
[10 30 50]
[2 5]


# Broadcasting

* Allows NumPy to perform arithmetic on arrays with **different shapes**.
* The smaller array is **broadcast** to match the shape of the larger one.

### Rules:

1. Dimensions must be equal or 1.
2. Operates element-wise after broadcasting.


In [11]:
a = np.array([1, 2, 3])
print(a + 10)  # [11 12 13]

a = np.array([[1], [2], [3]])
b = np.array([10, 20, 30])
print(a + b)

✅ WakaTime heartbeat sent at 1751694140.882681
[11 12 13]
[[11 21 31]
 [12 22 32]
 [13 23 33]]


# Arithmetic and Comparison

* Perform element-wise math or comparison operations.

###  Common Ops:

```python
+ - * / % // **  ==  !=  >  <  >=  <=
```


In [12]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)  # [5 7 9]
print(a * b)  # [4 10 18]
print(a < b)  # [True True True]

✅ WakaTime heartbeat sent at 1751694140.944541
[5 7 9]
[ 4 10 18]
[ True  True  True]


# Universal Functions (ufuncs)

### Theory:

* Optimized **element-wise functions**.
* Fast & vectorized.

### Common ufuncs:

```python
np.sqrt(), np.exp(), np.abs(), np.sin(), np.log()
```


In [13]:
a = np.array([1, 4, 9])
print(np.sqrt(a))   # [1. 2. 3.]
print(np.exp(a))    # [2.71 54.6 8103.08]

✅ WakaTime heartbeat sent at 1751694141.007748
[1. 2. 3.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03]


# Aggregation Functions

* Reduce data to a **summary statistic**.

### 🔸 Common:

```python
np.sum(), np.mean(), np.min(), np.max(), np.std()
```


In [14]:
a = np.array([[1, 2], [3, 4]])
print(np.sum(a))    # 10
print(np.mean(a))   # 2.5
print(np.max(a))    # 4

✅ WakaTime heartbeat sent at 1751694141.069768
10
2.5
4


# Axis-wise Operations

* `axis=0`: Column-wise
* `axis=1`: Row-wise


In [15]:
a = np.array([[1, 2], [3, 4]])
print(np.sum(a, axis=0))  # [4 6]
print(np.sum(a, axis=1))  # [3 7]

✅ WakaTime heartbeat sent at 1751694141.130623
[4 6]
[3 7]


# Conditional Functions

###  `np.where(condition, x, y)`

* Returns elements from `x` where `condition` is true, else from `y`.

###  `np.clip(arr, min_val, max_val)`

* Limits array values within bounds.

###  `np.any()` and `np.all()`

* Checks condition across entire array.



In [16]:
a = np.array([1, 2, 3, 4, 5])

print(np.where(a > 3, 1, 0))  # [0 0 0 1 1]
print(np.clip(a, 2, 4))       # [2 2 3 4 4]

print(np.any(a > 4))          # True
print(np.all(a > 0))          # True

✅ WakaTime heartbeat sent at 1751694141.192923
[0 0 0 1 1]
[2 2 3 4 4]
True
True


# More about this Section

---

## 1. `np.nonzero()` & `np.count_nonzero()`

### Use-case:

* Identify or count non-zero (or `True`) values — often used with boolean indexing.

In [17]:
a = np.array([0, 1, 0, 2, 3])
print(np.nonzero(a))        
print(np.count_nonzero(a))  

✅ WakaTime heartbeat sent at 1751694141.25377
(array([1, 3, 4]),)
3


## 2. `np.unique()` (with `return_counts`)

### Use-case:

* Get **distinct values** and how often each appears.

In [18]:
a = np.array([1, 2, 2, 2, 3, 3, 3, 3, 3])
u, counts = np.unique(a, return_counts=True)
print(u)       
print(counts)  

✅ WakaTime heartbeat sent at 1751694141.31691
[1 2 3]
[1 3 5]


## 3. `np.sort()` vs `np.argsort()`

### Use-case:

* Sort data or get the order of indices to sort.

In [19]:
a = np.array([3, 1, 2])
print(np.sort(a))     
print(np.argsort(a))  

✅ WakaTime heartbeat sent at 1751694141.38014
[1 2 3]
[1 2 0]


## 4. `np.argmax()`, `np.argmin()`

### Use-case:

* Get the index of the **max or min** value.


In [20]:
a = np.array([10, 20, 5, 40])
print(np.argmax(a))  
print(np.argmin(a))  

✅ WakaTime heartbeat sent at 1751694141.439596
3
2


## 5. `np.set_printoptions()`

### Use-case:

* Cleanly format large NumPy array output (like suppressing scientific notation).

In [21]:
np.set_printoptions(precision=2, suppress=True)
a = np.array([1.123456, 2.345678])
print(a)  

✅ WakaTime heartbeat sent at 1751694141.499366
[1.12 2.35]


## 6. Advanced Boolean Chaining

### Use-case:

* Combine multiple conditions with `&` and `|` (**not** `and` or `or`)

> Note: Always wrap each condition in parentheses!

In [22]:
a = np.array([1, 2, 3, 4, 5])
print(a[(a > 2) & (a < 5)]) 

✅ WakaTime heartbeat sent at 1751694141.560534
[3 4]


## 7. `np.allclose()` and `np.isclose()`

### Use-case:

* Compare floats with tolerance (avoid precision issues).

In [23]:
a = np.array([0.1 + 0.2])
b = np.array([0.3])
print(np.isclose(a, b))     
print(np.allclose(a, b))

✅ WakaTime heartbeat sent at 1751694141.622537
[ True]
True


## 8. Broadcasting with Dimensions

### Use-case:

* You can add new axes using `np.newaxis` or `reshape()` to trigger broadcasting.

In [24]:
a = np.array([1, 2, 3])
b = np.array([[10], [20]])
print(a + b)

✅ WakaTime heartbeat sent at 1751694141.685501
[[11 12 13]
 [21 22 23]]


## 9. Chain of Conditions with `np.where()`

### Use-case:

* Use `np.where()` with multiple `elif`-like conditions using nested calls.

In [25]:
a = np.array([70, 85, 60, 95])
result = np.where(a >= 90, 'A',
         np.where(a >= 80, 'B',
         np.where(a >= 70, 'C', 'D')))
print(result)  

✅ WakaTime heartbeat sent at 1751694141.745535
['C' 'B' 'D' 'A']


## 10. Bitwise Ops with Booleans

### Use-case:

* Logical operations across arrays: `np.logical_and()`, `np.logical_or()`, etc.


In [26]:
a = np.array([True, False, True])
b = np.array([False, False, True])
print(np.logical_and(a, b))  

✅ WakaTime heartbeat sent at 1751694141.805615
[False False  True]


---

# Summary for this Section

---

| Feature                        | Function(s) / Syntax                       | Description                                                                 |
|-------------------------------|--------------------------------------------|-----------------------------------------------------------------------------|
| Indexing & Slicing            | `a[i]`, `a[start:stop:step]`               | Access or extract elements using index or slice notation                    |
| Boolean Indexing              | `a[condition]`                             | Select elements that satisfy a condition                                   |
| Fancy Indexing                | `a[[i1, i2, ...]]`, `a[[rows], [cols]]`    | Use lists or arrays to pick multiple indices                                |
| Broadcasting                  | Auto expansion (e.g., `a + b`)             | Apply operations between arrays of different but compatible shapes          |
| Arithmetic Ops                | `+`, `-`, `*`, `/`, `**`                   | Element-wise arithmetic                                                     |
| Comparison Ops                | `==`, `!=`, `<`, `>`, `<=`, `>=`           | Element-wise comparison (returns boolean array)                             |
| Universal Functions (ufuncs)  | `np.sqrt()`, `np.exp()`, `np.log()`, etc.  | Fast element-wise operations                                                |
| Aggregation Functions         | `np.sum()`, `np.mean()`, `np.min()`        | Reduces an array to a single value                                          |
| Axis-wise Operations          | `np.sum(a, axis=0)`                        | Aggregation along rows or columns                                           |
| Conditional Selection         | `np.where(cond, x, y)`                     | Return elements based on condition                                          |
| Clipping                      | `np.clip(a, min, max)`                     | Restrict values within [min, max]                                           |
| Any / All                     | `np.any(cond)`, `np.all(cond)`             | Check if any/all elements satisfy condition                                 |
| Non-zero Index                | `np.nonzero(a)`                            | Return indices of non-zero (or `True`) elements                             |
| Count Non-zero                | `np.count_nonzero(a)`                      | Count number of non-zero values                                             |
| Unique Elements               | `np.unique(a)`, `return_counts=True`       | Get sorted unique elements and their frequency                              |
| Sort Values                   | `np.sort(a)`                               | Return sorted array                                                         |
| Sort Indices                  | `np.argsort(a)`                            | Return indices that would sort array                                        |
| Max / Min Index               | `np.argmax(a)`, `np.argmin(a)`             | Get index of max or min value                                               |
| Precision Display             | `np.set_printoptions()`                    | Format output (e.g., precision, suppress sci. notation)                     |
| Multiple Conditions           | `(a > x) & (a < y)`                        | Combine conditions with `&`, `|`, `~`                                       |
| Float Comparison              | `np.isclose(a, b)`, `np.allclose()`        | Compare floats with tolerance                                               |
| Logical Ops                   | `np.logical_and()`, `np.logical_or()`      | Perform element-wise boolean operations                                     |
| Nested Conditions             | `np.where(...np.where(...))`              | Apply multiple conditions using nested `where()`                            |
