In [1]:
import subprocess
from datetime import datetime
from IPython import get_ipython

# --- CONFIGURATION ---
NOTEBOOK_NAME = "Applications_Advanced_Concepts.ipynb"
PLUGIN_NAME = "jupyterlab/4.0.0"
LANGUAGE = "Python"
# ----------------------

def log_to_wakatime():
    timestamp = str(datetime.utcnow().timestamp())
    result = subprocess.run([
        "wakatime-cli",
        "--entity", NOTEBOOK_NAME,
        "--entity-type", "file",
        "--plugin", PLUGIN_NAME,
        "--language", LANGUAGE,
        "--write",
        "--time", timestamp
    ], capture_output=True, text=True)

    if result.returncode != 0:
        print("❌ WakaTime CLI Error:")
        print("STDOUT:", result.stdout)
        print("STDERR:", result.stderr)
    else:
        print("✅ WakaTime heartbeat sent at", timestamp)

def on_cell_run(execution_info):
    log_to_wakatime()

# Clear broken old handlers (if rerunning)
ip = get_ipython()
for cb in list(ip.events.callbacks['pre_run_cell']):
    if cb.__name__ == "<lambda>":
        ip.events.unregister('pre_run_cell', cb)

ip.events.register('pre_run_cell', on_cell_run)


# Advanced Concepts & Applications

---

## 1. Linear Algebra Operations

### `np.dot(a, b)`

* Computes dot product of 1D or 2D arrays.

### `a @ b` or `np.matmul(a, b)`

* Performs matrix multiplication.

### `a.T`

* Transposes the matrix.


In [2]:
import numpy as np
a = np.array([1, 2])
b = np.array([3, 4])
print(np.dot(a, b))

✅ WakaTime heartbeat sent at 1752323123.945285
11


In [3]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(A @ B)

✅ WakaTime heartbeat sent at 1752323124.162315
[[19 22]
 [43 50]]


In [4]:
a = np.array([[1, 2], [3, 4]])
print(a,"\n")
print(a.T)

✅ WakaTime heartbeat sent at 1752323124.217257
[[1 2]
 [3 4]] 

[[1 3]
 [2 4]]


## the linalg part stands for Linear Algebra. It is a submodule of NumPy

| Function                   | Description                            |
| -------------------------- | -------------------------------------- |
| `np.linalg.inv(a)`         | Inverse of a matrix                    |
| `np.linalg.det(a)`         | Determinant of a matrix                |
| `np.linalg.eig(a)`         | Eigenvalues and eigenvectors           |
| `np.linalg.solve(a, b)`    | Solves `ax = b` for `x`                |
| `np.linalg.norm(a)`        | Norm (magnitude) of a vector or matrix |
| `np.linalg.pinv(a)`        | Pseudo-inverse of a matrix             |
| `np.linalg.matrix_rank(a)` | Rank of a matrix                       |


### `np.linalg.inv(a)`

* Inverse of a square matrix.


### `np.linalg.det(a)`

* Returns determinant.


### `np.linalg.eig(a)`

* Returns eigenvalues and eigenvectors.


### `np.linalg.solve(A, b)`

* Solves system Ax = b.


In [5]:
a = np.array([[1, 2], [3, 4]])
print(np.linalg.inv(a))

✅ WakaTime heartbeat sent at 1752323124.272317
[[-2.   1. ]
 [ 1.5 -0.5]]


In [6]:
a = np.array([[1, 2], [3, 4]])
print(np.linalg.det(a))

✅ WakaTime heartbeat sent at 1752323124.32544
-2.0000000000000004


In [7]:
a = np.array([[1, 2], [2, 1]])
vals, vecs = np.linalg.eig(a)

✅ WakaTime heartbeat sent at 1752323124.380912


In [8]:
A = np.array([[2, 1], [1, 3]])
b = np.array([8, 13])
print(np.linalg.solve(A, b))

✅ WakaTime heartbeat sent at 1752323124.443703
[2.2 3.6]


## 2. Random Sampling & Distributions

### `np.random.choice(arr, size, replace)`

* Randomly samples elements.


### `np.random.normal(loc, scale, size)`

* Samples from normal (Gaussian) distribution.


### `np.random.binomial(n, p, size)`

* Samples from a binomial distribution.


In [9]:
arr = np.array([10, 20, 30])
print(np.random.choice(arr, 5, replace=True))

✅ WakaTime heartbeat sent at 1752323124.495204
[20 30 30 30 20]


In [10]:
print(np.random.normal(0, 1, 5))

✅ WakaTime heartbeat sent at 1752323124.746801
[ 0.62205588 -0.01029453 -0.59781221 -0.64440778 -1.79707333]


In [11]:
print(np.random.binomial(10, 0.5, 5))

✅ WakaTime heartbeat sent at 1752323124.799374
[5 6 6 4 5]


## 3. NaN and Inf Handling

### `np.isnan(arr)`

* Checks which elements are `NaN`.


### `np.isinf(arr)`

* Checks which elements are `inf`.


### `np.nanmean(arr)`

* Computes mean ignoring NaNs.


### `np.nan_to_num(arr)`

* Replaces `NaN` and `inf` with finite numbers.


In [12]:
a = np.array([1, np.nan, 3])
print(np.isnan(a))

✅ WakaTime heartbeat sent at 1752323124.853345
[False  True False]


In [13]:
a = np.array([1, np.inf, -np.inf])
print(np.isinf(a))

✅ WakaTime heartbeat sent at 1752323124.907074
[False  True  True]


In [14]:
a = np.array([1, 2, np.nan])
print(np.nanmean(a))

✅ WakaTime heartbeat sent at 1752323124.957871
1.5


In [15]:
a = np.array([np.nan, np.inf, -np.inf, 5])
print(np.nan_to_num(a))

✅ WakaTime heartbeat sent at 1752323125.01009
[ 0.00000000e+000  1.79769313e+308 -1.79769313e+308  5.00000000e+000]


## 4. File I/O Operations

### `np.save(filename, arr)`

* Save NumPy array to `.npy` binary file.

### `np.load(filename)`

* Load `.npy` binary file.

### `np.savetxt(filename, arr, delimiter=',')`

* Save array to `.txt` or `.csv`.

```python
arr = np.array([[1, 2], [3, 4]])
np.savetxt("data.csv", arr, delimiter=",")
```

### `np.loadtxt(filename, delimiter=',')`

* Load from `.txt` or `.csv`.

```python
data = np.loadtxt("data.csv", delimiter=",")
```

### `np.genfromtxt(filename, delimiter=',')`

* Similar to `loadtxt` but handles missing values.

```python
data = np.genfromtxt("data.csv", delimiter=",")
```


## 5. Memory Layout & Performance

### `.strides`

* Number of bytes to step in each dimension when traversing array.

### `order='C'` or `'F'`

* Row-major (`C`) or column-major (`F`) memory layout.


In [16]:

# C-order (default)
a = np.array([[1, 2],
              [3, 4]], order='C')

# F-order
b = np.array([[1, 2],
              [3, 4]], order='F')

print("C-order array:\n", a)
print("C-order strides:", a.strides)

print("\nF-order array:\n", b)
print("F-order strides:", b.strides)


✅ WakaTime heartbeat sent at 1752323125.063384
C-order array:
 [[1 2]
 [3 4]]
C-order strides: (16, 8)

F-order array:
 [[1 2]
 [3 4]]
F-order strides: (8, 16)


### `.view()`

* Creates a shallow copy (shares memory).

### `.copy()`

* Deep copy (separate memory).


In [17]:
a = np.array([1, 2, 3])
b = a.view()
b[0] = 100
print(a)  

✅ WakaTime heartbeat sent at 1752323125.115328
[100   2   3]


In [18]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print(a)  

✅ WakaTime heartbeat sent at 1752323125.167307
[1 2 3]


## 6. Structured Arrays

### Custom Data Type with Named Fields


In [19]:
dt = np.dtype([('name', 'U10'), ('age', 'i4')])
arr = np.array([('Alice', 25), ('Bob', 30)], dtype=dt)
print(arr['name'])  # ['Alice' 'Bob']
print(arr['age'])   # [25 30]

✅ WakaTime heartbeat sent at 1752323125.224534
['Alice' 'Bob']
[25 30]


### Convert to Record Array

In [20]:
rec_arr = arr.view(np.recarray)
print(rec_arr.name)

✅ WakaTime heartbeat sent at 1752323125.280446
['Alice' 'Bob']


## **Optional Topics (Rarely Used):**

### 1. **Masked Arrays**

* Useful when working with invalid or missing data without removing them.


### 2. **Broadcasting Tricks**

* E.g., creating grids without `meshgrid` using broadcasting.


### 3. **`np.vectorize()`**

* Vectorizes any Python function (less efficient than ufuncs, but useful).


### 4. **`np.fromfunction()`**

* Create arrays using a function over indices.
  

### 5. **`np.seterr()`**

* Control how NumPy handles floating-point errors (like divide-by-zero).


### 6. **`np.apply_along_axis()`**

* Apply a function along a specific axis of a 2D array.


In [21]:
import numpy.ma as ma
data = ma.masked_array([1, 2, 3, -99], mask=[0, 0, 0, 1])
print(data.mean())  # Ignores the masked value

✅ WakaTime heartbeat sent at 1752323125.337609
2.0


In [22]:
x = np.arange(3).reshape(3, 1)
y = np.arange(4)
grid = x + y  # Shape: (3, 4)

✅ WakaTime heartbeat sent at 1752323125.396733


In [23]:
def myfunc(x): return x ** 2
vfunc = np.vectorize(myfunc)
print(vfunc([1, 2, 3]))

✅ WakaTime heartbeat sent at 1752323125.45414
[1 4 9]


In [24]:
f = lambda i, j: i + j
a = np.fromfunction(f, (3, 3), dtype=int)
print(a)

✅ WakaTime heartbeat sent at 1752323125.510615
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [25]:
np.seterr(divide='ignore', invalid='ignore')

✅ WakaTime heartbeat sent at 1752323125.56606


{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [26]:
a = np.array([[1, 2], [3, 4]])
print(np.apply_along_axis(np.sum, axis=1, arr=a))  # [3, 7]

✅ WakaTime heartbeat sent at 1752323125.625298
[3 7]


## ✅ Summary Table

| Feature            | Function(s)                            | Description                                   |
| ------------------ | -------------------------------------- | --------------------------------------------- |
| Linear Algebra Ops | `dot`, `matmul`, `inv`, `det`, `solve` | Matrix math & systems of equations            |
| Random Sampling    | `choice`, `normal`, `binomial`         | Random draws from distributions               |
| NaN/Inf Handling   | `isnan`, `isinf`, `nanmean`            | Handle missing/infinite values                |
| File I/O           | `save`, `load`, `savetxt`, `loadtxt`   | Read/write arrays to files                    |
| Memory Layout      | `view()`, `copy()`, `strides`, `order` | Understand and optimize memory representation |
| Structured Arrays  | `dtype=[('name','U10'), ('age','i4')]` | Use arrays with named fields like databases   |

---